### ISSUE TITLE
Why is DEFAULT_SCOPE always included?

### ISSUE THREAD

**Issue by robskidmore** [microauth/microauth-google#2]
Just curios as to why 'https://www.googleapis.com/auth/plus.me' is merged into the scope array regardless of what is passed to it?

As it stands, even if I only want `userinfo.email` and `userinfo.profile` I still get everything from `plus.me` back as well.

**Comment by rapzo** [comment]
It shouldn't. Thanks for pointing it out. Fix on the way.

**Comment by remorses** [comment]
I get the error `Legacy People API has not been used in project ` because the google plus API is disabled by default as it is legacy now

Please replace the default scope with `https://www.googleapis.com/auth/userinfo.email`

**Comment by rapzo** [comment]
Slept on this one, sorry.
I'll take a look at it today.
Thank you for reminding me!

**Comment by rapzo** [comment]
Fixed. Don't forget to check the breaking changes (Google's).
